const citiesName = [
    {"id": 1, "label": "Islamabad"},
    {"id": 2, "label": "Ahmed Nager"},
    {"id": 3, "label": "Ahmadpur East"},
    {"id": 4, "label": "Ali Khan"},
    {"id": 5, "label": "Alipur"},
    {"id": 6, "label": "Arifwala"},
    {"id": 7, "label": "Attock"},
    {"id": 8, "label": "Bhera"},
    {"id": 9, "label": "Bhalwal"},
    {"id": 10, "label": "Bahawalnagar"},
    {"id": 11, "label": "Bahawalpur"},
    {"id": 12, "label": "Bhakkar"},
    {"id": 13, "label": "Burewala"},
    {"id": 14, "label": "Chillianwala"},
    {"id": 15, "label": "Chakwal"},
    {"id": 16, "label": "Chichawatni"},
    {"id": 17, "label": "Chiniot"},
    {"id": 18, "label": "Chishtian"},
    {"id": 19, "label": "Daska"},
    {"id": 20, "label": "Darya Khan"},
    {"id": 21, "label": "Dera Ghazi"},
    {"id": 22, "label": "Dhaular"},
    {"id": 23, "label": "Dina"},
    {"id": 24, "label": "Dinga"},
    {"id": 25, "label": "Dipalpur"},
    {"id": 26, "label": "Faisalabad"},
    {"id": 27, "label": "Fateh Jhang"},
    {"id": 28, "label": "Ghakhar Mandi"},
    {"id": 29, "label": "Gojra"},
    {"id": 30, "label": "Gujranwala"},
    {"id": 31, "label": "Gujrat"},
    {"id": 32, "label": "Gujar Khan"},
    {"id": 33, "label": "Hafizabad"},
    {"id": 34, "label": "Haroonabad"},
    {"id": 35, "label": "Hasilpur"},
    {"id": 36, "label": "Haveli Lakha"},
    {"id": 37, "label": "Jalalpur"},
    {"id": 38, "label": "Jattan"},
    {"id": 39, "label": "Jampur"},
    {"id": 40, "label": "Jaranwala"},
    {"id": 41, "label": "Jhang"},
    {"id": 42, "label": "Jhelum"},
    {"id": 43, "label": "Kalabagh"},
    {"id": 44, "label": "Karor Lal"},
    {"id": 45, "label": "Kasur"},
    {"id": 46, "label": "Kamalia"},
    {"id": 47, "label": "Kamoke"},
    {"id": 48, "label": "Khanewal"},
    {"id": 49, "label": "Khanpur"},
    {"id": 50, "label": "Kharian"},
    {"id": 51, "label": "Khushab"},
    {"id": 52, "label": "Kot Adu"},
    {"id": 53, "label": "Jauharabad"},
    {"id": 54, "label": "Lahore"},
    {"id": 55, "label": "Lalamusa"},
    {"id": 56, "label": "Layyah"},
    {"id": 57, "label": "Liaquat Pur"},
    {"id": 58, "label": "Lodhran"},
    {"id": 59, "label": "Malakwal"},
    {"id": 60, "label": "Mamoori"},
    {"id": 61, "label": "Mailsi"},
    {"id": 62, "label": "Mandi Bahauddin"},
    {"id": 63, "label": "Mian Channu"},
    {"id": 64, "label": "Mianwali"},
    {"id": 65, "label": "Multan"},
    {"id": 66, "label": "Murree"},
    {"id": 67, "label": "Muridke"},
    {"id": 68, "label": "Mianwali Bangla"},
    {"id": 69, "label": "Muzaffargarh"},
    {"id": 70, "label": "Narowal"},
    {"id": 71, "label": "Okara"},
    {"id": 72, "label": "Renala Khurd"},
    {"id": 73, "label": "Pakpattan"},
    {"id": 74, "label": "Pattoki"},
    {"id": 75, "label": "Pir Mahal"},
    {"id": 76, "label": "Qaimpur"},
    {"id": 77, "label": "Qila Didar"},
    {"id": 78, "label": "Rabwah"},
    {"id": 79, "label": "Raiwind"},
    {"id": 80, "label": "Rajanpur"},
    {"id": 81, "label": "Rahim Yar"},
    {"id": 82, "label": "Rawalpindi"},
    {"id": 83, "label": "Sadiqabad"},
    {"id": 84, "label": "Safdarabad"},
    {"id": 85, "label": "Sahiwal"},
    {"id": 86, "label": "Sangla Hill"},
    {"id": 87, "label": "Sarai Alamgir"},
    {"id": 88, "label": "Sargodha"},
    {"id": 89, "label": "Shakargarh"},
    {"id": 90, "label": "Sheikhupura"},
    {"id": 91, "label": "Sialkot"},
    {"id": 92, "label": "Sohawa"},
    {"id": 93, "label": "Soianwala"},
    {"id": 94, "label": "Siranwali"},
    {"id": 95, "label": "Talagang"},
    {"id": 96, "label": "Taxila"},
    {"id": 97, "label": "Toba Tek"},
    {"id": 98, "label": "Vehari"},
    {"id": 99, "label": "Wah Cantonment"},
    {"id": 100, "label": "Wazirabad"},
    {"id": 101, "label": "Badin"},
    {"id": 102, "label": "Bhirkan"},
    {"id": 103, "label": "Rajo Khanani"},
    {"id": 104, "label": "Chak"},
    {"id": 105, "label": "Dadu"},
    {"id": 106, "label": "Digri"},
    {"id": 107, "label": "Diplo"},
    {"id": 108, "label": "Dokri"},
    {"id": 109, "label": "Ghotki"},
    {"id": 110, "label": "Haala"},
    {"id": 111, "label": "Hyderabad"},
    {"id": 112, "label": "Islamkot"},
    {"id": 113, "label": "Jacobabad"},
    {"id": 114, "label": "Jamshoro"},
    {"id": 115, "label": "Jungshahi"},
    {"id": 116, "label": "Kandhkot"},
    {"id": 117, "label": "Kandiaro"},
    {"id": 118, "label": "Karachi"},
    {"id": 119, "label": "Kashmore"},
    {"id": 120, "label": "Keti Bandar"},
    {"id": 121, "label": "Khairpur"},
    {"id": 122, "label": "Kotri"},
    {"id": 123, "label": "Larkana"},
    {"id": 124, "label": "Matiari"},
    {"id": 125, "label": "Mehar"},
    {"id": 126, "label": "Mirpur Khas"},
    {"id": 127, "label": "Mithani"},
    {"id": 128, "label": "Mithi"},
    {"id": 129, "label": "Mehrabpur"},
    {"id": 130, "label": "Moro"},
    {"id": 131, "label": "Nagarparkar"},
    {"id": 132, "label": "Naudero"},
    {"id": 133, "label": "Naushahro Feroze"},
    {"id": 134, "label": "Naushara"},
    {"id": 135, "label": "Nawabshah"},
    {"id": 136, "label": "Nazimabad"},
    {"id": 137, "label": "Qambar"},
    {"id": 138, "label": "Qasimabad"},
    {"id": 139, "label": "Ranipur"},
    {"id": 140, "label": "Ratodero"},
    {"id": 141, "label": "Rohri"},
    {"id": 142, "label": "Sakrand"},
    {"id": 143, "label": "Sanghar"},
    {"id": 144, "label": "Shahbandar"},
    {"id": 145, "label": "Shahdadkot"},
    {"id": 146, "label": "Shahdadpur"},
    {"id": 147, "label": "Shahpur Chakar"},
    {"id": 148, "label": "Shikarpaur"},
    {"id": 149, "label": "Sukkur"},
    {"id": 150, "label": "Tangwani"},
    {"id": 151, "label": "Tando Adam"},
    {"id": 152, "label": "Tando Allahyar"},
    {"id": 153, "label": "Tando Muhammad"},
    {"id": 154, "label": "Thatta"},
    {"id": 155, "label": "Umerkot"},
    {"id": 156, "label": "Warah"},
    {"id": 157, "label": "Abbottabad"},
    {"id": 158, "label": "Adezai"},
    {"id": 159, "label": "Alpuri"},
    {"id": 160, "label": "Akora Khattak"},
    {"id": 161, "label": "Ayubia"},
    {"id": 162, "label": "Banda Daud"},
    {"id": 163, "label": "Bannu"},
    {"id": 164, "label": "Batkhela"},
    {"id": 165, "label": "Battagram"},
    {"id": 166, "label": "Birote"},
    {"id": 167, "label": "Chakdara"},
    {"id": 168, "label": "Charsadda"},
    {"id": 169, "label": "Chitral"},
    {"id": 170, "label": "Daggar"},
    {"id": 171, "label": "Dargai"},
    {"id": 172, "label": "Darya Khan"},
    {"id": 173, "label": "Dera Ismail"},
    {"id": 174, "label": "Doaba"},
    {"id": 175, "label": "Dir"},
    {"id": 176, "label": "Drosh"},
    {"id": 177, "label": "Hangu"},
    {"id": 178, "label": "Haripur"},
    {"id": 179, "label": "Karak"},
    {"id": 180, "label": "Kohat"},
    {"id": 181, "label": "Kulachi"},
    {"id": 182, "label": "Lakki Marwat"},
    {"id": 183, "label": "Latamber"},
    {"id": 184, "label": "Madyan"},
    {"id": 185, "label": "Mansehra"},
    {"id": 186, "label": "Mardan"},
    {"id": 187, "label": "Mastuj"},
    {"id": 188, "label": "Mingora"},
    {"id": 189, "label": "Nowshera"},
    {"id": 190, "label": "Paharpur"},
    {"id": 191, "label": "Pabbi"},
    {"id": 192, "label": "Peshawar"},
    {"id": 193, "label": "Saidu Sharif"},
    {"id": 194, "label": "Shorkot"},
    {"id": 195, "label": "Shewa Adda"},
    {"id": 196, "label": "Swabi"},
    {"id": 197, "label": "Swat"},
    {"id": 198, "label": "Tangi"},
    {"id": 199, "label": "Tank"},
    {"id": 200, "label": "Thall"},
    {"id": 201, "label": "Timergara"},
    {"id": 202, "label": "Tordher"},
    {"id": 203, "label": "Awaran"},
    {"id": 204, "label": "Barkhan"},
    {"id": 205, "label": "Chagai"},
    {"id": 206, "label": "Dera Bugti"},
    {"id": 207, "label": "Gwadar"},
    {"id": 208, "label": "Harnai"},
    {"id": 209, "label": "Jafarabad"},
    {"id": 210, "label": "Jhal Magsi"},
    {"id": 211, "label": "Kacchi"},
    {"id": 212, "label": "Kalat"},
    {"id": 213, "label": "Kech"},
    {"id": 214, "label": "Kharan"},
    {"id": 215, "label": "Khuzdar"},
    {"id": 216, "label": "Killa Abdullah"},
    {"id": 217, "label": "Killa Saifullah"},
    {"id": 218, "label": "Kohlu"},
    {"id": 219, "label": "Lasbela"},
    {"id": 220, "label": "Lehri"},
    {"id": 221, "label": "Loralai"},
    {"id": 222, "label": "Mastung"},
    {"id": 223, "label": "Musakhel"},
    {"id": 224, "label": "Nasirabad"},
    {"id": 225, "label": "Nushki"},
    {"id": 226, "label": "Panjgur"},
    {"id": 227, "label": "Pishin valley"},
    {"id": 228, "label": "Quetta"},
    {"id": 229, "label": "Sherani"},
    {"id": 230, "label": "Sibi"},
    {"id": 231, "label": "Sohbatpur"},
    {"id": 232, "label": "Washuk"},
    {"id": 233, "label": "Zhob"},
    {"id": 234, "label": "Ziarat"}
  ]

  export default citiesName;