const data = {
  total: 5000,
  sub_total: 4500,
  user_id: 1,
  role_id: 1,
  added_by: "admin",
  gst: 126.0,
  shipment_charges: 260.0,
  manual: "true",
  delivery_method: "cod",
  shipping_address: "28 A mian meer crown plaza hotel, lahore",
  //"promo_code": "",
  paid: "false",
  status: "dispatched",
  cod: "true",
  payment_method: "cod",
  ledger_description: "fluffer jacket 29",
  vat: 26.0,
  order_data: [
    {
      article_id: 3,
      pre_post: "0001104659-14",
      p_id: "00SCS",
      is_scanned: 0,
      size: "small",
      qty: 1,
      total_price: 3000,
      single_price: 1000,
      actual_single_price: 1000,
      on_sale: "false",
    },
  ],
  billing_data: {
    phone: 3224546704,
    address: "28 A mian meer crown plaza hotel, lahore",
    city: "lahore",
    postcode: "lahore",
    state: "Punjab",
  },
  contact_data: {
    phone: 3224546704,
    name: "affi affi",
    email: "affi@gmail.com",
  },
  shipping_data: {
    phone: 3224546704,
    address: "28 A mian meer crown plaza hotel, lahore",
    city: "lahore",
    postcode: "lahore",
    state: "Punjab",
  },
};
